version: "3.1"
services:
    mysql:
        image: "mysql:8.0"
        working_dir: /app
        volumes:
            - ".:/app"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "8071:3306"

    webserver:
        image: "nginx:alpine"
        working_dir: /app
        volumes:
            - ".:/app"
            - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "/storage/app/public/post_images"
            - "/storage/app/public/profile_images"
        ports:
            - "8069:80"
        env_file:
            - .env

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - ".:/app"
            - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
            - "/storage/app/public/post_images"
            - "/storage/app/public/profile_images"
        env_file:
            - .env
